[run]
timeout = "120s"

[output]
formats = "colored-line-number"

[linters]
enable = [
    "gocyclo", "unconvert", "goimports", "unused",
    "misspell", "nakedret", "errcheck", "revive", "ineffassign",
    "goconst", "govet", "unparam", "gofmt"
]

[issues]
exclude-use-default = false
