apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cap-infra-dns.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name:  {{ include "cap-infra-dns.serviceAccountName" .}}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "cap-infra-dns.fullname" . }}
